### PR TITLE
Add creation settings

### LINKED ISSUE #258: Add provenance information for each variable, including privacy parameters
Currently there is some provenance information in the distribution section. However, this does not include any information how it was created, just by whom.

### PR DESCRIPTION
**Pull request by qubixes**
Fixes #258 

This PR tries to add some more information about how the variable was created. It probably needs a little bit more testing.

### CODE REVIEW

**Review by Samuwhale — APPROVED** [review]
Looks good to me!

**Review by vankesteren — COMMENTED** [review]
Looks good, the logic looks done! One question: does "creation settings" still cover the meaning? Would "fit parameters", fitting config, estimation settings be better?

**Comment by qubixes** [comment]
> Looks good, the logic looks done! One question: does "creation settings" still cover the meaning? Would "fit parameters", fitting config, estimation settings be better?

I think those are okay as well. However, I think the point is that some distributions are not estimated / fitted, but simply defined. If you have a suggestion that also covers that use case, then that might be better than creation_settings.

**Comment by vankesteren** [comment]
After thinking more, I'd go for either:
- fit_method
- creation_method

I still think "fit" works, as the user is also "fitting", just not doing ML estimation

**Comment by qubixes** [comment]
> After thinking more, I'd go for either:
> 
>     * fit_method
> 
>     * creation_method
> 
> 
> I still think "fit" works, as the user is also "fitting", just not doing ML estimation
> 
> You can choose and merge!!

Okay, creation_method it is then!

**Pull request merged**
