### PR TITLE
Discrete normal

### LINKED ISSUE #214: Add normal and truncatednormal discrete distributions
If you measure many people's height in cm, rounded to the nearest cm, you will get a discrete normal distribution. 

We have this situation in our YOUth data. Would be nice to support it!

### PR DESCRIPTION
**Pull request by vankesteren**
Fixes #214

I am subclassing the continuous distributions. This makes the code very small but it might not be the most "clean" way of creating these discrete distributions.

### CODE REVIEW

**Comment by qubixes** [comment]
Very nice and clean! I added the tests as well, feel free to merge!

**Review by qubixes — APPROVED** [review]

**Comment by vankesteren** [comment]
Our CI is failing on macos-latest in the nbval. Is this something we can fix easily or should I just merge?

**Review by Samuwhale — APPROVED** [review]
Looks good to me! I'll be sure to add them to the developer's guide section I'm currently working on as well (as I'm working on an overview of the distributions there).

**Comment by Samuwhale** [comment]
You can ignore the nbval problem and merge. For some reason tests (for various previous PRs too) keep failing on `df.describe()` in the notebook in the mac tests. But they work when running on my m1 mac, and have worked on @qubixes mac as well. Just a weird bug, but not related to our codebase.

**Pull request merged**
