### PR TITLE
Add export functionality to TOML in addition to JSON

### LINKED ISSUE #322: Error messaging if toml file is not well formatted
I am creating synthetic data with a toml file. When the toml file is not well formatted metsyn throws this error message:

```
staig001@busoni autumn-fair % metasyn create-meta  --config event_config.toml
Traceback (most recent call last):
  File "/Users/staig001/.local/bin/metasyn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/__main__.py", line 80, in main
    create_metadata()
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/__main__.py", line 127, in create_metadata
    meta_frame = MetaFrame.from_config(meta_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/metaframe.py", line 169, in from_config
    return cls.fit_dataframe(None, meta_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/metaframe.py", line 140, in fit_dataframe
    var = MetaVar(
          ^^^^^^^^
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/var.py", line 72, in __init__
    if self.prop_missing < -1e-8 or self.prop_missing > 1 + 1e-8:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'float'
staig001@busoni autumn-fair % metasyn create-meta  --config event_config.toml
Traceback (most recent call last):
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/config.py", line 102, in from_toml
    config_dict = tomllib.load(handle)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tomllib/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tomllib/_parser.py", line 127, in loads
    raise suffixed_err(
tomllib.TOMLDecodeError: Expected newline or end of document after a statement (at line 44, column 8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/staig001/.local/bin/metasyn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/__main__.py", line 80, in main
    create_metadata()
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/__main__.py", line 120, in create_metadata
    meta_config = MetaConfig.from_toml(args.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/staig001/.local/pipx/venvs/metasyn/lib/python3.12/site-packages/metasyn/config.py", line 109, in from_toml
    raise ValueError(f"It appears '{Path(config_fp).name}' is a"
ValueError: It appears 'event_config.toml' is a '.toml' file. To load a MetaConfig, provide it as a .toml file.
```

Is it possible to distinguish whether the file was not a toml file or whether it is an incorrectly formatted toml file and adjust the feedback in the error message?

### LINKED ISSUE #323: Parsing of var_types
Parsing of var_types gives error which is not understandable:

```
var_type = "float"
distribution = {implements = "core.uniform", parameters = {lower = 0, upper = 15}}
```
gives error:
```
ValueError: Cannot find distribution with name 'core.uniform'.
```

### PR DESCRIPTION
**Pull request by qubixes**
This also adds a new configuration TOML version: 1.1

Changes include that now defaults can be set for the data_free variables. For example, you don't need to type in the prop_missing for each variable anymore, you can set the default in the [defaults] section. You can also have default distributions now per variable type -> e.g. all continuous variables could by default be assigned the normal distributions.

TODO:
- [x] Documentation
- [x] Tests
- [x] Sample configuration files (also one file with all distributions).

Fixes #323 Fixes #322

### CODE REVIEW

**Comment by qubixes** [comment]
@vankesteren I haven't completely finished yet, but it would be nice to get your input on the import/export functionality of `MetaFrame`. Currently we have `mf.from_json`, `mf.to_json` and `mf.export`. This works alright for json, however from toml this becomes very confusing, since we would have a `mf.from_toml` that would not take a configuration toml file. My proposal is to instead use `mf.load` and `mf.store` with suffix detection and `mf.load_{suffix}` and `mf.store_{suffix}` for direct load/store. The old methods will have a deprecation warning attached, but will still work for one or two minor versions of metasyn. What do you think?

**Comment by vankesteren** [comment]
Agreed!

**Comment by vankesteren** [comment]
maybe load and save instead of load and store, those names are a bit more common

**Comment by qubixes** [comment]
Okay, I'll change it into load and save then, that sounds good to me as well.

**Comment by qubixes** [comment]
@vankesteren I have finished this PR. I have edited the images, but I didn't find them all, so I have removed the few that I can't find. I have changed all Exported MetaFrame -> GMF file for consistency, the documentation itself also needs to change some at some point, but for now this is okay as far as I am concerned.

**Review by vankesteren — APPROVED** [review]
fix the suggestions and then merge

**Pull request merged**
