### PR TITLE
Add VarSpec to remove the warnings from the examples

### PR DESCRIPTION
**Pull request by qubixes**
This is one way to do it. Another would be to get a demo file without a unique column. It might be helpful to show the VarSpec off anyway?

### CODE REVIEW

**Review by vankesteren — CHANGES_REQUESTED** [review]
i prefer the other solution you mentioned. the initial example should be as simple as possible

**Comment by qubixes** [comment]
Shall I adjust the fruit dataset then?

**Comment by vankesteren** [comment]
hmm, does spaceship give an error? otherwise we can do that one. Fruit is take. directly from the polars website so let's keep it the same as there.

we can also just create / find a new example dataset like "questionnaire" or so, with demographics and some questionnaire likely scale answers and an open question

**Comment by qubixes** [comment]
Spaceship does not give an error, however the image in the readme is about fruit... The spaceship dataset is quite wide to show easily like that.

**Comment by vankesteren** [comment]
I've reconsidered. I now think that receiving a warning is not so bad in the main example. Maybe we can leave it as-is and update/improve the warning note instead?

**Comment by qubixes** [comment]
Sure, I can think about that. It does sound a little bit like something has gone wrong, which is not necessarily the case.

**Comment by vankesteren** [comment]
Is there something like a "note" in python rather than a "warning"?

**Comment by qubixes** [comment]
We could use the logging module in the standard library. This might be redirected to stdout and not stderr though, which I think is the case of the warnings module?

**Pull request closed without merging**
